; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

# DEFAULT: WHICH TO RUN - RUNS TEENSY ENV
[platformio]
default_envs = nano

# nanoatmega328 - mimic arduino nano environment as if its in arduino ide
# replace arduino nano with whatever micrcontroller you're using
[env:nano]
platform = atmelavr
board = nanoatmega328
framework = arduino

# PUT LIBRARIES HERE
lib_deps = 
    arduino-libraries/SD

# DESKTOP - for general c++ coding
[env:native]
platform = native