; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

# DEFAULT: WHICH TO RUN - RUNS TEENSY ENV
[platformio]
default_envs = teensy41

# TEENSY - mimic teensy environment as if its in arduino ide
# replace teensy with whatever micrcontroller you're using
[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
# PUT LIBRARIES HERE
lib_deps = 
    https://github.com/Saddleback-College-Rocketry-Team/Library.git

# DESKTOP - for general c++ coding
[env:native]
platform = native